name: city_guide_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

workspace:
  - packages/theme
  - packages/data
  - packages/domain
  - packages/core
  - packages/auth
  - packages/home
  - packages/login
  - packages/debug
  - packages/presentation
  - packages/dependencies

dependencies:
  flutter:
    sdk: flutter
  theme: ^1.0.0
  data: ^1.0.0
  domain: ^1.0.0
  core: ^1.0.0
  auth: ^1.0.0
  home: ^1.0.0
  login: ^1.0.0
  debug: ^1.0.0
  presentation: ^1.0.0
  dependencies: ^1.0.0
  firebase_core: ^3.12.1
  
dev_dependencies:
  dart_code_metrics:
    git:
      url: git@github.com:TarasSk/dart_code_metrics.git
      ref: main
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.2
  test: ^1.21.0

dependency_overrides:
  analyzer: 5.13.0

flutter:
  uses-material-design: true
