name: debug
description: Debug feature package
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.24.0

