name: dependencies
description: Shared external dependencies for the City Guide app.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  
  # Navigation
  go_router: ^15.1.3
  
  # DI & Utils
  get_it: ^8.0.3
  equatable: ^2.0.7
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  meta: ^1.16.0
  
  # Firebase / Auth
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  
  # Network
  http: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
