name: core
description: Core package containing shared infrastructure (logger, router, DI, etc.)
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dependencies: ^1.0.0
  auth: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.24.0

