name: home
description: Home feature package
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dependencies: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.14
  go_router_builder: ^2.7.1
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.24.0
